config/routes.rb
LongLivePaper::Application.routes.draw do
  
  resources :articles
  root :to => 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Amazon::WebServices::MTurk
  protect_from_forgery with: :exception
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
#  before_action :authenticate_user!
  
  def initialize
     ymlstring = "AWSAccessKeyId: #{ENV['AWS_ACCESS_KEY_ID']}\nAWSAccessKey: #{ENV['AWS_SECRET_ACCESS_KEY']}\nHost: Production"

    File.open(Rails.root.join('config', 'mturk.yml'), 'w') do |f|  
      f.puts ymlstring 
    end  
    
    @mturk = Amazon::WebServices::MechanicalTurkRequester.new :Config => Rails.root.join('config', 'mturk.yml')
    #@mturk = Amazon::WebServices::MechanicalTurkRequester.new :Config => ymlstring
    #@mturk = Amazon::WebServices::MechanicalTurkRequester.new :Config => Rails.root.join('config', 'mturk.yml')
    #@mturk = Amazon::WebServices::MechanicalTurkRequester.new(
      # :AWSAcessKeyId => ENV['AWS_ACCESS_KEY_ID'],
      # :AWSAccessKey  => ENV['AWS_SECRET_ACCESS_KEY'])
    #@mturk = Amazon::WebServices::MechanicalTurkRequester.new :Host => :Production
    super
  end
    
  def index
  #  openRequests = Article.where("title = nil")
    checkForResults()
    @articles = Article.where("status = 'answered'")
    @article = Article.new
  end

  def create
    @article = Article.new(params.require(:article).permit(:image))
    if @article.save
      flash[:notice] = "Successfully submitted article."    
      createNewHit(@article)
      redirect_to "/"
    else
      render :action => 'new'
    end
  end

  def destroy
    id = params[:id]
    Article.find(id).destroy
    redirect_to "/"
  end


  def checkForResults()
    reviewableHits = @mturk.GetReviewableHITs(:Status => "Reviewable")[:GetReviewableHITsResult][:HIT] || []

      if !reviewableHits.is_a?(Array)
        reviewableHits=[reviewableHits]
      end
     
        reviewableHits.each do |hitId|
          hitId = hitId[:HITId]
          article = Article.find_by(HIT_ID: hitId)  
          # hit = @mturk.GetHIT(:HITId => hitId)[:HIT]
          answer = @mturk.GetAssignmentsForHIT(:HITId => hitId)[:GetAssignmentsForHITResult][:Assignment]
          if answer != nil
            assignmentId = answer[:AssignmentId]
            if answer[:AssignmentStatus] != "Approved"
              @mturk.ApproveAssignment(:AssignmentId => assignmentId)
            end   
            answerHash = @mturk.simplifyAnswer(answer[:Answer])
            article.headline = answerHash["headline"]
            article.url = answerHash["url"]
            article.periodical = answerHash["periodical"]
            article.status = "answered"
            article.save
     
            @mturk.DisposeHIT(:HITId => hitId)
            
          end
   
          # if hit[:Expiration] < Time.now
          #   @mturk.DisposeHIT(:HITId => hitId)[:GetAssignmentsForHITResult][]
          
          # end
        end


      
    

  end


  def createNewHit(article)
    title = "Write the words from an image and find website"
    desc = "Transcribe the headline shown in an image of an article and find the url of that article."
    keywords = "image, write, transcription, URL"
    numAssignments = 1
    reward = { :Amount => 0.20, :CurrencyCode => 'USD' }
    assignmentDurationInSeconds = 60 * 60 # 1 hour
    lifetimeInSeconds = 60 * 60 * 3 # 6 hours
    hitLayout = "3UF1487ESTUD3X3IG0S1GCD5RCM906"
    hitLayoutParams = {:Name => 'image_url', :Value => article.image_url}
    # qualRequirement = {
    #   :QualificationTypeId => '2ARFPLSP75KLA8M8DH1HTEQVJT3SY6', 
    #   :Comparator => 'Exists'
    # }  

    # begin
    result = @mturk.createHIT( :Title => title,
                    :Description => desc,
                    :MaxAssignments => numAssignments,
                    :Reward => reward,
                    :Keywords => keywords,
                    :HITLayoutId => hitLayout,
                    :HITLayoutParameter => hitLayoutParams,
                    :LifetimeInSeconds => lifetimeInSeconds,
                    :AssignmentDurationInSeconds => assignmentDurationInSeconds,
                    # :QualificationRequirement => qualRequirement
                    )
  # rescue Amazon::WebServices::Util::ValidationException => e 
  #  puts e.inspect
  # end
    puts "Created HIT: #{result[:HITId]}"
    puts "Url: #{getHITUrl( result[:HITTypeId] )}"
    article.HIT_ID = result[:HITId]
    article.status = "pending"
    article.save
  end

  def getHITUrl( hitTypeId )
    if @mturk.host =~ /sandbox/
      "http://workersandbox.mturk.com/mturk/preview?groupId=#{hitTypeId}" # Sandbox Url
    else
      "http://mturk.com/mturk/preview?groupId=#{hitTypeId}" # Production Url
    end
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/index.html.erb
 

<!-- 
<div ng-controller="Ctrl">
  <form ng-submit="addImg()">
    <input ng-model="picture" type="file" id="take-picture" capture="camera" accept="image/*" value="Take picture">
  </form> -->

<!--   <input type="file" capture="camera" accept="image/*" id="takePictureField">
  </br>
  <img id="yourimage" style="width:60%"> -->

<!--  <img ng-if="image" src="{{image}}" alt="">
  <form action="">
    <input my-upload type="file" name="upload" capture="camera" accept="image/*">  
  </form> -->
<!--   <input type="file" file-model="myFile" capture="camera" accept="image/*">
  <button ng-click="uploadFile()">upload me</button> -->

<div class="row">
  <p>New Search</p>
  <%= form_for @article, :html => {:multipart => true} do |f| %>
    
      
      <input id="article_image" name="article[image]" type="file" capture="camera" accept="image/*" >
      </br>
    <p><%= f.submit value="Find article"%></p>
  <% end %>
</div>
</br>
</br>

<div class="row">  
  <div>
  <p>Previous Searches</p>
  <table class="table">
    <thead>
      <tr>
        <th>Date Requested</th>
        <th>Periodical</th>
        <th>Article</th>
      </tr>
    </thead>  
    <tbody>
      <% @articles.each do |a| %>
          <tr>
            <td><%=a.created_at%></br>
                <%= link_to "Delete", article_path(a.id), method: :delete %></td>
            <td><%=a.periodical%></td>
            <td><a href="<%=a.url%>"><%=a.headline%></a></td>
          </tr>
      <%end%>
    </tbody>
  </table>   
  </div>                 
</div>

<!-- <form name="takePicture" ng-controller="Ctrl"> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- <html ng-app="sharePaper"> -->
<html>
<head>
  <title>LongLivePaper</title>

  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
</head>
<body>
<nav class="navbar navbar-default navbar-top" role="navigation">
  <div>
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/articles">SocialPaper</a>
    </div>

  </div>
</nav>

  <div class="container">
    <% if notice %>
      <p class="alert alert-notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-error"><%= alert %></p>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>